### ISSUE TITLE
Plans for an English blog?

### ISSUE THREAD

**Issue by jishanshaikh4** [Junhyunny/junhyunny.github.io#1]
I see there is great technical content right here, you have some plans for English?

**Comment by Junhyunny** [comment]
I'm really happy to hear that. I have a plan to translate my posts into English, but not quite soon. You can use a translation plugin in Chrome. It is almost similar to what I want to say. If you want more specific information or insight, I can help you.

**Comment by jishanshaikh4** [comment]
Yes, I am aware of the plugin. I would be free (I suppose) in the upcoming weekend or in the meantime, will try to raise the PR for English posts.

**Comment by Junhyunny** [comment]
That's lovely suggestion, but I think about that more. Sorry.
