### ISSUE TITLE
Change of username

### ISSUE THREAD

**Issue by ma7dev** [Junhyunny/junhyunny.github.io#34]
Hi!

I have noticed that you have referenced my tutorial of `Ngrok, running multiple ports at once (works for free version)` in [this post](https://github.com/Junhyunny/junhyunny.github.io/blob/58a35367c085fed7b6ae7b82f0218797be4c7786/_posts/2022/2022-09-17-ngrok-multiple-ports-tunneling-on-free-plan.md?plain=1#L81) but the referenced gist link is broken because I have changed my username from `sudomaze` to `ma7dev`.

**Comment by Junhyunny** [comment]
Oh thanks for your information.
